name: BridgeBattle
version: 2.0
main: org.minigame.minigame.BridgeBattle
api-version: "1.20"

commands:
  bridge:
    description: Main Bridge Battle command
    usage: /bridge <join|leave|start|end|setspawn|setbridgezone|top>
  b:
    description: Quick join command
    usage: /b

permissions:
  bridge.admin:
    description: Admin commands
    default: op